displayName: Enterprise RAG Load Test
testPlan: loadtest.jmx
description: ''
engineInstances: 1
testId: enterprise-rag-load-test
testType: JMX
splitAllCSVs: True
configurationFiles:
- dataset.csv
failureCriteria:
- HTTP Request: p95(response_time_ms) > 60000
- HTTP Request: p95(latency) > 60000
secrets:
- name: loadtestSecret
  value: https://kv0-b43jjtlauvxek.vault.azure.net/secrets/orchestrator-host--functionKey/f9f0e3238dd44b94a3f05b98b2e38588
properties:
  userPropertyFile: loadtest.properties
autoStop:
  errorPercentage: 90
  timeWindow: 60
